### ISSUE TITLE
Add VC Playground Issuer dids to registry

### ISSUE THREAD

**Issue by bmuramatsu** [digitalcredentials/community-registry#9]
To ensure the credentials hosted on the VC Playground, https://vcplayground.org/issuer, will verify in LCW and VerifierPlus, we'll need to add the dids (that we support, did:key and did:web) to a registry used by our software.

If we wanted to focus on the "academic" credentials then we should make sure that the:
Alumni, JFF Open Badge, JFF x vc-edu PF2, JFF x vc-edu PF3 and TLN dids are in the registry.

There may be value in listing the others.

**Comment by kayaelle** [comment]
Thanks, @bmuramatsu. Will keep assigned to you while the issuer info is being collected.

**Comment by kayaelle** [comment]
We can grab DIDs from the playground and add to community registry.
